### ISSUE TITLE
关于按需引入

### ISSUE THREAD

**Issue by worldzhao** [cuke-ui/cuke-ui#17]
antd手动按需引入代码如下：
![image](https://user-images.githubusercontent.com/25662450/58463590-ba138700-8166-11e9-9d2c-800d205242ba.png)

可见每个组件打包后的style目录下存在两个文件 index.js以及css.js require了所需的less文件以及css文件，这样保证了组件之间的样式依赖可以在按需的条件下引入

cuke-ui的手动按需引入是这样的
![image](https://user-images.githubusercontent.com/25662450/58463781-14144c80-8167-11e9-8ea8-79f77c28341d.png)
只引入的style.less，假如Button组件还依赖另外一些组件的样式，是不是就gg了（的确也有一些组件是这样的）。

当然，使用babel-plugin-import插件没问题，因为他引用的是style.js这个文件，我看在写这个文件的时候把其他组件样式依赖也require了。

其实我想知道antd那种是如何根据style.js生成css.js  因为只能引入less的话对项目来说是不是有一些挑剔？还需要项目去配置loader。

就是babel-plugin-import配置的style属性值为`css`

`style:'css'`

我最近一直在学习你们的项目，但是似乎cuke-ui也没有实现这一步，导致按需引入无法引入css只能引入less，对使用非less预处理器的项目不太友好。

谢谢 望回复！

**Comment by worldzhao** [comment]
额，我在antd-tools的gulpfile.js文件里看到了相关代码 我先研究下

**Comment by worldzhao** [comment]
![image](https://user-images.githubusercontent.com/25662450/58465591-994d3080-816a-11e9-8275-5a885f35969f.png)
![image](https://user-images.githubusercontent.com/25662450/58465608-a1a56b80-816a-11e9-988a-7718e762a903.png)
希望能有所帮助

**Comment by lijinke666** [comment]
是的 当时偷懒只实现了 按需加载 `less` , 如需支持 `css` 还需要一个 `css.js` 把当前组件所以依赖的 样式 require 进去

**Comment by lijinke666** [comment]
> ![image](https://user-images.githubusercontent.com/21015895/58466893-2beecf00-816d-11e9-9f1c-5e8b40e5d1df.png)

这里是 文档没有更新, 在新版我提供了一个 `style.js` 解决了您的 问题

> 假如Button组件还依赖另外一些组件的样式，是不是就gg了（的确也有一些组件是这样的）

比如 `Pagination` 组件

```js
require("../styles");

require("../button/style");

require("../select/style");

require("./styles.less");
```

**Comment by worldzhao** [comment]
了解啦，多谢，这个项目给了我很多很多帮助，点赞！
