### ISSUE TITLE
TurnTable bug

### ISSUE THREAD

**Issue by fikyair** [cuke-ui/cuke-ui#7]
在点击TurnTable抽奖的后，在旋转的时候切换到其他浏览器Tab页，会无限制的旋转下去，直到再切回抽奖页面。

**Comment by lijinke666** [comment]
😁感谢 反馈,  已记录 !

**Comment by fikyair** [comment]
我对这个项目很感兴趣，可不可以邀我进组织啊:yum:

**Comment by fikyair** [comment]
> 感谢 反馈, 已记录 !
 @lijinke666 我对这个项目很感兴趣，可不可以邀我进组织啊:yum:
